import type { Metadata } from "next";

import { inter } from "@/app/fonts";
import "./globals.css";

import { Suspense } from "react";
import Header from "@/app/components/header";
import AuthProvider from "@/app/utils/SessionProvider";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "TechAss",
  description: "Generated by the hands of the greatest web developer",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen antialiased`}>
        <AuthProvider session={session}>
          <Suspense>
            <Header />
          </Suspense>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
