import type { Metadata } from "next";

import "./globals.css";

import Header from "@/app/components/header";
import { Suspense } from "react";

import { inter } from "@/app/fonts";

export const metadata: Metadata = {
  title: "TechAss",
  description: "Generated by the hands of the greatest web developer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen antialiased`}>
        <Suspense>
          <Header />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
